# Generated by Django 5.2.4 on 2025-07-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="dorm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="email",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="is_pickup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
