# Generated by Django 5.2.4 on 2025-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
